site_name: scRNA-Seq Public Data
pages:
    - Home: index.md
    - Mouse Brain: mouse-brain.md
    - Mouse Development: mouse-dev.md
    - Mouse Tissues: mouse-tissues.md
    - Human Tissues: human-tissues.md
theme: 'material'
docs_dir: 'website'
site_dir: 'docs'
google_analytics:
  - 'UA-91539252-1'
  - 'auto'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/hemberg-lab/public-scrnaseq-datasets'
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
markdown_extensions:
  - admonition

repo_name: hemberg-lab/public-scrnaseq-datasets
repo_url: https://github.com/hemberg-lab/public-scrnaseq-datasets/
